### PR TITLE
Added KeyCode to avoid GLFW_KEY_*

### PR DESCRIPTION
**Pull request by meruiden**
I have made some changes to your input class
Input uses KeyCode instead of GLFW_KEY_*.
BUT GLFW_KEY_* is still working if used.

I think this makes a lot more sense than the GLFW_KEY_*.
It also reduces the amount of times the keyword GLFW if used in projects.
You don't want to worry about GLFW when working in RT2D i guess :D

Hope u like it ;)

### CODE REVIEW

**Comment by rktrlng** [comment]
Ah yes, this is much nicer. Especially because it doesn't break anything short term. Thanks!

Couple of things though,
- how about including the content of keycode.h into input.h? They belong strictly together. Might as well be in a single header file.
- there's no need to '#include <rt2d/singleton.h>' in input.h (did you run into trouble with that?). They're totally separate things. Input doesn't need to know it's a singleton. You can instantiate *any* class as a singleton by 'wrapping' it with the template. Without doing anything special in the class itself. That's the beauty of it :)

Agree?

**Comment by meruiden** [comment]
Hi,
The reason i made a seperate header file is because i did not want to make the input.h a mess. But i will replace it to input.h :) the reason the singleton is included is because i was expirimenting with something and forgot to clear the unclude, by bad ;), i will chabge that to

**Comment by rktrlng** [comment]
Notice how in the ASCII table the decimal number 32 corresponds with the character ' ' (a space)? That's also the first entry in the enum and GLFW definitions. 65 = 'A' etcetera.

That's why I had this:

	bool getKey(char key) { return getKey((int) key); }

So you could do:

	if ( input->getKey('A') ) { /*...*/ }

I see you changed that to `bool getKey(int key)`. That works, but it's clearer how it was. You did cast it correctly to return a (KeyCode) though.

I'm only interested in the ASCII values. I want a char. The key definitions with values over 255 can't be typed on a keyboard in code on a keyboard (backspace or escape for example). The code reflected the intention perfectly.

In fact, this is one of those spare moments where I DIDN'T abuse the char type.

This is what it should be I think(*):

	/// @param key as char (ie: getKey('A') )
	bool getKey(char key) { return getKey((KeyCode)key); }

What you say?

(*) I used getKey('a') in the documentation which was wrong: lowercase letters 97 and up are not used.

**Comment by meruiden** [comment]
I'm sorry for removing it, i thought you were indeed abusing it 😄

**Comment by rktrlng** [comment]
Cool! :smile:
Thanks for sharing!

**Comment by rktrlng** [comment]
Sigh... I did it again.
First merge, then close.

**Comment by rktrlng** [comment]
I removed `bool getKey*(int key)` by the way. It's not needed any more. Only char and KeyCode.
Thanks again!

**Comment by meruiden** [comment]
Ah okay :) the reason i left it in is when people pull the new update they wont get any compiling errors where they used GLFW_KEY_*

**Comment by rktrlng** [comment]
Hmmm yes. That might be a bit of a show stopper.

Fair enough. I've put it back for now with a `@deprecated` command in doxygen, but it will be gone eventually.

People better get used to it quick. Thanks!

**Pull request merged**
