### PR TITLE
Entity enabled state

### PR DESCRIPTION
**Pull request by jessegall**
Added entity an enabled state. enabled false will disable the rendering and update.

### CODE REVIEW

**Comment by jessegall** [comment]
Mhhh.. dat config file though ... :P

**Comment by jessegall** [comment]
Mhh, I messed up.. enabled(bool e) {enabled = true;} should ofc be enabled = e

**Comment by jessegall** [comment]
I'll close this one. Open one later

**Comment by rktrlng** [comment]
Cool, thanks! :)

**Pull request closed without merging**
